version: '3.3'
services:
  dev_rasa:
    image: rasa/rasa:latest-full
    ports:
      - 5005:5005
    volumes:
      - ./:/
    command:
      - run
  dev_action_server:
    image: rasa/rasa-sdk:latest
    volumes:
      - ./actions:/actions
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DB=1
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  redis_data:
    driver: local

configs:

  